module.exports = [
  {
    id: 'human',
    tradeRate: 2,
    discs: 13,
    initialS: 3,
    initialM: 4,
    initialG: 3,
    colons: 3,
    sectors: ['221', '223', '225', '227', '229', '231'],
    emplacements: ['alliance', 'twin', 'twin', 'twin', 'twin'],
    technos: ['star_base'],
    initialShips: ['interceptor'],
    prices: {
      interceptor: 3,
      cruiser: 5,
      dreadnought: 8,
      starbase: 3,
      orbital: 4,
      monolith: 10,
    },
    initialBadges: 0,
    tags: [], // ['chooseTile', 'fragilePop', 'ancientFriend']
    activeActions: { exp: 1, dev: 1, ame: 2, con: 2, dep: 3, inf: 2 },
    passedActions: { ame: 1, con: 1, dep: 1 },
    schematics: {
      interceptor: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'interceptor_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'thr_1' },
          { id: 'L', part: 'pow_3' },
          { id: 'B', part: null },
        ],
      },
      cruiser: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'cruiser_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      dreadnought: {
        stats: { ini: 0, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'dreadnought_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T1', part: 'can_1' },
          { id: 'T2', part: 'can_1' },
          { id: 'B1', part: 'hul_1' },
          { id: 'B2', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      base: {
        stats: { ini: 4, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'base_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'C', part: null },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'hul_1' },
          { id: 'TR', part: 'can_1' },
          { id: 'BR', part: 'hul_1' },
        ],
      },
    },
  },
  {
    id: 'eridani',
    color: 'red',
    tradeRate: 3,
    discs: 11,
    initialS: 2,
    initialM: 4,
    initialG: 26,
    colons: 3,
    sectors: ['222'],
    emplacements: ['twin', 'twin', 'twin', 'twin'],
    technos: ['shd_1', 'thr_2', 'can_2'],
    initialShips: ['interceptor'],
    prices: {
      interceptor: 3,
      cruiser: 5,
      dreadnought: 8,
      starbase: 3,
      orbital: 4,
      monolith: 10,
    },
    initialBadges: 2,
    tags: [],
    activeActions: { exp: 1, dev: 1, ame: 2, con: 2, dep: 2, inf: 2 },
    passedActions: { ame: 1, con: 1, dep: 1 },
    schematics: {
      interceptor: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'interceptor_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'thr_1' },
          { id: 'L', part: 'pow_3' },
          { id: 'B', part: null },
        ],
      },
      cruiser: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'cruiser_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      dreadnought: {
        stats: { ini: 0, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'dreadnought_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T1', part: 'can_1' },
          { id: 'T2', part: 'can_1' },
          { id: 'B1', part: 'hul_1' },
          { id: 'B2', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      base: {
        stats: { ini: 4, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'base_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'C', part: null },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'hul_1' },
          { id: 'TR', part: 'can_1' },
          { id: 'BR', part: 'hul_1' },
        ],
      },
    },
  },
  {
    id: 'planta',
    color: 'green',
    tradeRate: 3,
    discs: 13,
    initialS: 3,
    initialM: 4,
    initialG: 2,
    colons: 4,
    sectors: ['226'],
    emplacements: ['alliance', 'twin', 'twin', 'twin'],
    technos: ['star_base'],
    initialShips: ['interceptor'],
    prices: {
      interceptor: 3,
      cruiser: 5,
      dreadnought: 8,
      starbase: 3,
      orbital: 4,
      monolith: 10,
    },
    initialBadges: 0,
    tags: ['fragilePop', 'scoreForTiles'],
    activeActions: { exp: 2, dev: 1, ame: 2, con: 2, dep: 2, inf: 2 },
    passedActions: { ame: 1, con: 1, dep: 1 },
    schematics: {
      interceptor: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'interceptor_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'thr_1' },
          { id: 'L', part: 'pow_3' },
          { id: 'B', part: null },
        ],
      },
      cruiser: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'cruiser_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      dreadnought: {
        stats: { ini: 0, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'dreadnought_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T1', part: 'can_1' },
          { id: 'T2', part: 'can_1' },
          { id: 'B1', part: 'hul_1' },
          { id: 'B2', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      base: {
        stats: { ini: 4, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'base_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'C', part: null },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'hul_1' },
          { id: 'TR', part: 'can_1' },
          { id: 'BR', part: 'hul_1' },
        ],
      },
    },
  },
  {
    id: 'hydran',
    color: 'blue',
    tradeRate: 3,
    discs: 13,
    initialS: 6,
    initialM: 2,
    initialG: 2,
    colons: 3,
    sectors: ['224'],
    emplacements: ['alliance', 'twin', 'twin', 'twin'],
    technos: ['adv_s'],
    initialShips: ['interceptor'],
    prices: {
      interceptor: 3,
      cruiser: 5,
      dreadnought: 8,
      starbase: 3,
      orbital: 4,
      monolith: 10,
    },
    initialBadges: 0,
    tags: [],
    activeActions: { exp: 1, dev: 2, ame: 2, con: 2, dep: 2, inf: 2 },
    passedActions: { ame: 1, con: 1, dep: 1 },
    schematics: {
      interceptor: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'interceptor_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'thr_1' },
          { id: 'L', part: 'pow_3' },
          { id: 'B', part: null },
        ],
      },
      cruiser: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'cruiser_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      dreadnought: {
        stats: { ini: 0, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'dreadnought_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T1', part: 'can_1' },
          { id: 'T2', part: 'can_1' },
          { id: 'B1', part: 'hul_1' },
          { id: 'B2', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      base: {
        stats: { ini: 4, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'base_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'C', part: null },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'hul_1' },
          { id: 'TR', part: 'can_1' },
          { id: 'BR', part: 'hul_1' },
        ],
      },
    },
  },
  {
    id: 'orion',
    color: 'black',
    tradeRate: 4,
    discs: 13,
    initialS: 3,
    initialM: 4,
    initialG: 3,
    colons: 3,
    sectors: ['232'],
    emplacements: ['twin', 'twin', 'twin', 'twin', 'pv'],
    technos: ['neutron', 'shd_1'],
    initialShips: ['cruiser'],
    prices: {
      interceptor: 3,
      cruiser: 5,
      dreadnought: 8,
      starbase: 3,
      orbital: 4,
      monolith: 10,
    },
    initialBadges: 0,
    tags: [],
    activeActions: { exp: 1, dev: 1, ame: 2, con: 2, dep: 2, inf: 2 },
    passedActions: { ame: 1, con: 1, dep: 1 },
    schematics: {
      interceptor: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'interceptor_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'thr_1' },
          { id: 'L', part: 'pow_3' },
          { id: 'B', part: null },
        ],
      },
      cruiser: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'cruiser_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      dreadnought: {
        stats: { ini: 0, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'dreadnought_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T1', part: 'can_1' },
          { id: 'T2', part: 'can_1' },
          { id: 'B1', part: 'hul_1' },
          { id: 'B2', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      base: {
        stats: { ini: 4, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'base_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'C', part: null },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'hul_1' },
          { id: 'TR', part: 'can_1' },
          { id: 'BR', part: 'hul_1' },
        ],
      },
    },
  },
  {
    id: 'mechanema',
    color: 'white',
    tradeRate: 3,
    discs: 13,
    initialS: 3,
    initialM: 4,
    initialG: 2,
    colons: 3,
    sectors: ['230'],
    emplacements: ['twin', 'twin', 'twin', 'twin'],
    technos: ['cpm_2'],
    initialShips: ['interceptor'],
    prices: {
      interceptor: 2,
      cruiser: 4,
      dreadnought: 7,
      starbase: 2,
      orbital: 3,
      monolith: 8,
    },
    initialBadges: 0,
    tags: [],
    activeActions: { exp: 1, dev: 1, ame: 3, con: 3, dep: 2, inf: 2 },
    passedActions: { ame: 1, con: 1, dep: 1 },
    schematics: {
      interceptor: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'interceptor_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'thr_1' },
          { id: 'L', part: 'pow_3' },
          { id: 'B', part: null },
        ],
      },
      cruiser: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'cruiser_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      dreadnought: {
        stats: { ini: 0, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'dreadnought_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T1', part: 'can_1' },
          { id: 'T2', part: 'can_1' },
          { id: 'B1', part: 'hul_1' },
          { id: 'B2', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      base: {
        stats: { ini: 4, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'base_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'C', part: null },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'hul_1' },
          { id: 'TR', part: 'can_1' },
          { id: 'BR', part: 'hul_1' },
        ],
      },
    },
  },
  {
    id: 'draco',
    color: 'yellow',
    tradeRate: 3,
    discs: 13,
    initialS: 4,
    initialM: 3,
    initialG: 2,
    colons: 3,
    sectors: ['228'],
    emplacements: ['twin', 'twin', 'twin', 'twin'],
    technos: ['thr_2'],
    initialShips: ['interceptor'],
    prices: {
      interceptor: 3,
      cruiser: 5,
      dreadnought: 8,
      starbase: 3,
      orbital: 4,
      monolith: 10,
    },
    initialBadges: 0,
    tags: ['chooseTile', 'ancientFriend', 'scoreForAncients'],
    activeActions: { exp: 1, dev: 1, ame: 2, con: 2, dep: 2, inf: 2 },
    passedActions: { ame: 1, con: 1, dep: 1 },
    schematics: {
      interceptor: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'interceptor_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'thr_1' },
          { id: 'L', part: 'pow_3' },
          { id: 'B', part: null },
        ],
      },
      cruiser: {
        stats: { ini: 1, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'cruiser_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T', part: 'can_1' },
          { id: 'B', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      dreadnought: {
        stats: { ini: 0, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'dreadnought_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'T1', part: 'can_1' },
          { id: 'T2', part: 'can_1' },
          { id: 'B1', part: 'hul_1' },
          { id: 'B2', part: 'hul_1' },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'pow_3' },
          { id: 'TR', part: null },
          { id: 'BR', part: 'thr_1' },
        ],
      },
      base: {
        stats: { ini: 4, pow: 0, cmp: 0, shd: 0, hul: 0, thr: 0 },
        ihm: 'base_std',
        parts: [
          { id: 'hull', part: null },
          { id: 'C', part: null },
          { id: 'TL', part: 'cmp_1' },
          { id: 'BL', part: 'hul_1' },
          { id: 'TR', part: 'can_1' },
          { id: 'BR', part: 'hul_1' },
        ],
      },
    },
  },
];
