module.exports = [
  // Center

  {
    id: '001',
    ring: 0,
    group: 'root',
    background: 'center',
    vp: 4,
    label: 'center',
    tags: ['center', 'artefact'],
    planets: ['G', 'G', 'S', 'S+', 'M', 'M+'],
    exits: [1, 1, 1, 1, 1, 1],
  },

  // Guardians

  {
    id: '271',
    ring: 2,
    group: 'guardian',
    background: 'guardian',
    vp: 2,
    label: 'Omega Fornacis',
    tags: ['guardian', 'artefact'],
    planets: ['G', 'S', 'M+'],
    exits: [1, 1, 0, 1, 1, 1],
  },
  {
    id: '272',
    ring: 2,
    group: 'guardian',
    background: 'guardian',
    vp: 2,
    label: 'Sigma Hydrae',
    tags: ['guardian', 'artefact'],
    planets: ['G', 'M', 'S+'],
    exits: [1, 1, 0, 1, 1, 1],
  },
  {
    id: '273',
    ring: 2,
    group: 'guardian',
    background: 'guardian',
    vp: 2,
    label: 'Theta Ophiuchi',
    tags: ['guardian', 'artefact'],
    planets: ['G', 'M', 'M+'],
    exits: [1, 1, 0, 1, 1, 1],
  },
  {
    id: '274',
    ring: 2,
    group: 'guardian',
    background: 'guardian',
    vp: 2,
    label: 'Alpha Lyncis',
    tags: ['guardian', 'artefact'],
    planets: ['G', 'S', 'S+'],
    exits: [1, 1, 0, 1, 1, 1],
  },

  // SECTOR I

  {
    id: '101',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Castor',
    tags: ['ancient'],
    planets: ['G', 'M', 'M+'],
    exits: [1, 1, 1, 1, 1, 0],
  },
  {
    id: '102',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Pollux',
    tags: [],
    planets: ['S', 'S'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '103',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Beta Leonis',
    tags: [],
    planets: ['S', 'G'],
    exits: [1, 1, 1, 1, 1, 0],
  },
  {
    id: '104',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Arcturus',
    tags: ['double'],
    planets: ['S', 'S+', 'M', 'M+'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '105',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Zeta Herculis',
    tags: ['ancient'],
    planets: ['G', 'S', 'M+'],
    exits: [1, 1, 1, 1, 1, 0],
  },
  {
    id: '106',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Capella',
    tags: [],
    planets: ['S', 'M'],
    exits: [1, 1, 1, 1, 0, 0],
  },
  {
    id: '107',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 3,
    label: 'Aldebaran',
    tags: ['artefact'],
    planets: ['S+', 'G', 'M+'],
    exits: [1, 1, 1, 1, 1, 0],
  },
  {
    id: '108',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Mu Cassiopeiae',
    tags: ['ancient'],
    planets: ['S', 'G+', 'A'],
    exits: [1, 1, 1, 1, 1, 0],
  },
  {
    id: '109',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 4,
    label: 'Alpha Lacertae',
    tags: ['double', 'artefact'],
    planets: ['G', 'M'],
    exits: [1, 1, 1, 1, 1, 0],
  },
  {
    id: '110',
    ring: 1,
    group: 'root',
    background: 'sector1',
    vp: 2,
    label: 'Iota Boötis',
    tags: ['gift'],
    planets: ['G+', 'A+'],
    exits: [1, 1, 1, 0, 1, 0],
  },

  // SECTOR II

  {
    id: '201',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 1,
    label: 'Alpha Centauri',
    tags: [],
    planets: ['M', 'A'],
    exits: [1, 0, 1, 0, 1, 0],
  },
  {
    id: '202',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 2,
    label: 'Fomalhaut',
    tags: ['artefact'],
    planets: ['S', 'S+'],
    exits: [1, 0, 1, 0, 1, 0],
  },
  {
    id: '203',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 2,
    label: 'Chi Draconis',
    tags: ['double'],
    planets: ['S', 'M', 'G+'],
    exits: [1, 1, 1, 0, 1, 0],
  },
  {
    id: '204',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 2,
    label: 'Vega',
    tags: ['ancient', 'artefact'],
    planets: ['A', 'M+', 'G+'],
    exits: [1, 1, 1, 0, 1, 0],
  },
  {
    id: '205',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 1,
    label: 'Mu Herculis',
    tags: ['artefact'],
    planets: ['G', 'G+', 'S+'],
    exits: [1, 1, 1, 0, 0, 0],
  },
  {
    id: '206',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 1,
    label: 'Epsilon Indi',
    tags: ['gift'],
    planets: ['M'],
    exits: [1, 1, 1, 0, 1, 0],
  },
  {
    id: '207',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 2,
    label: 'Zeta Reticuli',
    tags: ['gift'],
    planets: [],
    exits: [1, 1, 0, 1, 0, 0],
  },
  {
    id: '208',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 2,
    label: 'Iota Persei',
    tags: ['gift'],
    planets: [],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '209',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 1,
    label: 'Delta Eridani',
    tags: [],
    planets: ['G', 'S'],
    exits: [1, 1, 1, 0, 1, 0],
  },
  {
    id: '210',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 1,
    label: 'Psi Capricorni',
    tags: [],
    planets: ['G', 'M'],
    exits: [1, 1, 0, 0, 1, 0],
  },
  {
    id: '211',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 1,
    label: 'Delta Aquilae',
    tags: ['ancient'],
    planets: ['G', 'A', 'M+'],
    exits: [1, 1, 1, 1, 0, 0],
  },
  {
    id: '214',
    ring: 2,
    group: 'root',
    background: 'sector2',
    vp: 2,
    label: 'Delta Monocerotis',
    tags: ['ancient'],
    planets: ['S', 'M+', 'A+'],
    exits: [1, 1, 1, 1, 1, 0],
  },

  // SECTOR III

  {
    id: '301',
    ring: 3,
    group: 'root',
    vp: 2,
    background: 'sector3',
    label: 'Zeta Draconis',
    tags: ['double', 'artefact'],
    planets: ['G', 'S', 'M+'],
    exits: [1, 0, 1, 1, 0, 0],
  },
  {
    id: '302',
    ring: 3,
    group: 'root',
    vp: 2,
    background: 'sector3',
    label: 'Gamma Serpentis',
    tags: ['ancient', 'artefact'],
    planets: ['G+', 'S+', 'M'],
    exits: [1, 0, 0, 1, 1, 0],
  },
  {
    id: '303',
    ring: 3,
    group: 'root',
    vp: 2,
    background: 'sector3',
    label: 'Eta Cephei',
    tags: ['ancient', 'artefact'],
    planets: ['A', 'G+', 'S+'],
    exits: [1, 0, 1, 0, 0, 0],
  },
  {
    id: '304',
    ring: 3,
    group: 'root',
    vp: 2,
    background: 'sector3',
    label: 'Theta Pegasi',
    tags: [],
    planets: ['G+', 'M'],
    exits: [1, 0, 0, 1, 0, 0],
  },
  {
    id: '305',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Lambda Serpentis',
    tags: ['ancient'],
    planets: ['M', 'S'],
    exits: [1, 1, 0, 1, 0, 0],
  },
  {
    id: '306',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Beta Centauri',
    tags: [],
    planets: ['G', 'M'],
    exits: [1, 0, 1, 0, 0, 0],
  },
  {
    id: '307',
    ring: 3,
    group: 'root',
    vp: 2,
    background: 'sector3',
    label: 'Sigma Sagittarii',
    tags: [],
    planets: ['G', 'S+'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '308',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Kappa Scorpii',
    tags: [],
    planets: ['S', 'M+'],
    exits: [0, 0, 1, 1, 0, 1],
  },
  {
    id: '309',
    ring: 3,
    group: 'root',
    vp: 2,
    background: 'sector3',
    label: 'Phi Piscium',
    tags: [],
    planets: ['G', 'S+'],
    exits: [1, 0, 0, 1, 0, 1],
  },
  {
    id: '310',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Nu Phoenicis',
    tags: [],
    planets: ['S', 'M'],
    exits: [1, 0, 0, 1, 0, 0],
  },
  {
    id: '311',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Canopus',
    tags: ['gift'],
    planets: ['M'],
    exits: [1, 0, 1, 1, 0, 0],
  },
  {
    id: '312',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Antares',
    tags: ['gift'],
    planets: ['M'],
    exits: [1, 1, 0, 1, 0, 0],
  },
  {
    id: '313',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Alpha Ursae Minoris',
    tags: ['gift'],
    planets: ['A'],
    exits: [1, 0, 0, 1, 0, 0],
  },
  {
    id: '314',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Spica',
    tags: ['gift'],
    planets: ['A'],
    exits: [1, 1, 1, 0, 0, 0],
  },
  {
    id: '315',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Epsilon Aurigae',
    tags: ['gift'],
    planets: [],
    exits: [1, 0, 0, 1, 0, 1],
  },
  {
    id: '316',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Iota Carinae',
    tags: ['gift'],
    planets: [],
    exits: [1, 1, 0, 1, 0, 0],
  },
  {
    id: '317',
    ring: 3,
    group: 'root',
    vp: 2,
    background: 'sector3',
    label: 'Beta Crucis',
    tags: [],
    planets: ['G', 'G+'],
    exits: [1, 1, 0, 0, 0, 0],
  },
  {
    id: '318',
    ring: 3,
    group: 'root',
    vp: 1,
    background: 'sector3',
    label: 'Gamma Velorum',
    tags: [],
    planets: ['A', 'M+'],
    exits: [0, 1, 1, 0, 0, 0],
  },

  // WORMHOLES

  {
    id: '281',
    ring: 2,
    group: 'wormhole',
    vp: 2,
    label: 'Delta Corvi',
    tags: ['gift', 'wormhole'],
    background: 'home',
    planets: ['G', 'S'],
    exits: [1, 0, 1, 1, 0, 1],
  },
  {
    id: '381',
    ring: 3,
    group: 'wormhole',
    vp: 1,
    label: 'Beta Sextantis',
    tags: ['gift', 'wormhole'],
    background: 'home',
    planets: ['M', 'G'],
    exits: [1, 0, 0, 1, 1, 0],
  },
  {
    id: '382',
    ring: 3,
    group: 'wormhole',
    vp: 1,
    label: 'Zeta Chamaeleontis',
    tags: ['gift', 'wormhole'],
    background: 'home',
    planets: ['M', 'S'],
    exits: [1, 0, 1, 1, 0, 0],
  },

  // HOME WORLDS

  {
    id: '221',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Procyon',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'S+', 'G', 'G+', 'M'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '222',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Epsilon Eridani',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['G', 'G+', 'S', 'S+'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '223',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Altair',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'S+', 'G', 'G+', 'M'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '224',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Beta Hydri',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S+', 'G', 'M+'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '225',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Eta Cassiopeiae',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'S+', 'G', 'G+', 'M'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '226',
    ring: 2,
    group: 'home',
    vp: 3,
    label: '61 Cygni',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'M'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '227',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Sirius',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'S+', 'G', 'G+', 'M'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '228',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Sigma Draconis',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'G', 'M+'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '229',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Tau Ceti',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'S+', 'G', 'G+', 'M'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '230',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Lambda Aurigae',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'M+', 'G', 'G+'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '231',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Delta Parvonis',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'S+', 'G', 'G+', 'M'],
    exits: [1, 1, 0, 1, 1, 0],
  },
  {
    id: '232',
    ring: 2,
    group: 'home',
    vp: 3,
    label: 'Rigel',
    tags: ['home', 'artefact'],
    background: 'home',
    planets: ['S', 'G+', 'M', 'M+'],
    exits: [1, 1, 0, 1, 1, 0],
  },
];
